US593021: Updated to run on Java 17
Autoscaler/autoscaler pull request #108
Opened 2022-11-09 12:52 UTC by michael-bryson

2022-11-09 12:53 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=Autoscaler&REPO_NAME=autoscaler&BRANCH_NAME=US593021) to go ahead and create the build...

2022-11-09 12:57 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/Autoscaler/job/Autoscaler~autoscaler~US593021~CI

2022-11-09 14:03 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/Autoscaler_CI_autoscaler_US593021

2022-11-15 17:25 UTC, dermot-hardy requested changes

2022-11-15 17:25 UTC, dermot-hardy commented on release-notes-2.0.0.md
> +- US593021: Nashorn script engine is no longer supported.
Unless I'm missing something this is not a breaking change for the autoscaler.

2022-11-15 17:26 UTC, michael-bryson commented on release-notes-2.0.0.md
> +- US593021: Nashorn script engine is no longer supported.
I didn't think so but they are listed under Apollo Workers for fortify. If that is only for fortify and not relevant then I can revert the version change.

2022-11-15 17:28 UTC, dermot-hardy commented on release-notes-2.0.0.md
> +- US593021: Nashorn script engine is no longer supported.
Yes it's just for Fortify.

2022-11-15 17:31 UTC, michael-bryson commented on release-notes-2.0.0.md
> +- US593021: Nashorn script engine is no longer supported.
Reverted.

2022-11-15 17:34 UTC, dermot-hardy approved these changes

2022-11-16 12:39 UTC, merged