US957002: Replace Kubernetes Java Client with caf-kuberentes-client
Autoscaler/autoscaler pull request #175
Opened 2024-08-29 12:24 UTC by rorytorneymf

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=957002

2024-08-29 12:26 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://sou-jenkins2.swinfra.net/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=Autoscaler&REPO_NAME=autoscaler&BRANCH_NAME=US957002) to go ahead and create the build...

2024-08-29 12:33 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://sou-jenkins2.swinfra.net/job/Autoscaler/job/Autoscaler~autoscaler~US957002~CI

2024-08-29 13:06 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/Autoscaler_CI_autoscaler_US957002

2024-08-29 13:14 UTC, rorytorneymf commented on pom.xml
> +                <version>1.0.0-US957002-SNAPSHOT</version>
Update before merging.

2024-09-06 04:12 UTC, dermot-hardy requested changes

2024-09-06 04:12 UTC, dermot-hardy commented on autoscale-source-kubernetes/src/main/java/com/github/autoscaler/source/kubernetes/K8sServiceSource.java
> +            scalingConfigurations.addAll(appsV1Api.listAppsV1NamespacedDeployment("private")
Should this be `.listAppsV1NamespacedDeployment(namespace)` rather than `.listAppsV1NamespacedDeployment("private")`?

2024-09-06 04:12 UTC, dermot-hardy commented on autoscale-source-kubernetes/src/main/java/com/github/autoscaler/source/kubernetes/K8sServiceSourceProvider.java
> +        } catch (final Exception e) {
I assume catching unchecked exceptions is not intended, so change this to:

```suggestion
        } catch (final ConfigurationException | FailedToCreateKubernetesClientException e) {
```

If catching unchecked exceptions is intentional then be explicit about it:

```suggestion
        } catch (final ConfigurationException | FailedToCreateKubernetesClientException | RuntimeException e) {
```

2024-09-06 04:12 UTC, dermot-hardy commented on autoscale-scaler-kubernetes/src/main/java/com/github/autoscaler/scaler/kubernetes/K8sServiceScaler.java
> +                final CoreV1Api.APIlistCoreV1NamespacedPodRequest request = coreV1Api.listCoreV1NamespacedPod("private");
Is this hardcoded `"private"` right?  Should it be `deploymentId.namespace`?

2024-09-06 04:12 UTC, dermot-hardy commented on autoscale-scaler-kubernetes/src/main/java/com/github/autoscaler/scaler/kubernetes/K8sHealthCheck.java
> -    private K8sHealthCheck()
Why are we dropping the private default constructor?

2024-09-06 14:45 UTC, dermot-hardy approved these changes

2024-09-06 15:42 UTC, merged