SCMOD-3298: Set dropwizard version to 1.3.2
Autoscaler/autoscaler pull request #20
Opened 2018-05-18 13:59 UTC by rado-straka

2018-05-18 14:06 UTC, dermot-hardy commented
Is there a developer build for this?  Has it been dev tested?

2018-05-23 11:43 UTC, dermot-hardy requested changes
Can this be done using the BOM the same way the WorkerFramework is done:
https://github.com/WorkerFramework/worker-framework/pull/66

2018-05-25 14:58 UTC, rado-straka commented
Updated

2018-05-25 20:44 UTC, dermot-hardy approved these changes

2018-05-25 20:44 UTC, dermot-hardy commented on release-notes-1.3.0.md
> +    (https://github.com/dropwizard/dropwizard/tree/v1.3.2))
Doesn't look right:
[https://github.com/Autoscaler/autoscaler/blob/8866d84/release-notes-1.3.0.md](https://github.com/Autoscaler/autoscaler/blob/8866d84bfcd403a59fc5a507555751b05c0c0fc8/release-notes-1.3.0.md)

2018-05-25 20:44 UTC, dermot-hardy commented on autoscale-acceptance-tests/pom.xml
> +</project>
Take a new line

2018-05-25 20:44 UTC, dermot-hardy commented on autoscale-acceptance-tests/src/integration-test/java/com/hpe/caf/autoscale/tests/AutoscalerIT.java
> +public class AutoscalerIT
Class should be `final`

2018-05-25 20:44 UTC, dermot-hardy commented on autoscale-acceptance-tests/src/integration-test/java/com/hpe/caf/autoscale/tests/AutoscalerIT.java
> +    public HttpResponse healthCheck(String requestUrl) throws IOException {
Parameter should be `final`.

2018-05-29 08:36 UTC, merged