SCMOD-4018: Updated Marathon Autoscaler to use PATCH
Autoscaler/autoscaler pull request #21
Opened 2018-05-31 11:45 UTC by rado-straka

https://jira.autonomy.com/browse/SCMOD-4018

2018-05-31 14:51 UTC, dermot-hardy requested changes

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
Remove this comment - all open-source artifacts are in Maven Central (or The Central Repository as it calls itself these days).

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/MarathonServiceScaler.java
> +import java.util.*;
List out classes explicitly - don't use star imports.

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/MarathonServiceScaler.java
> +        } catch (Exception e) {
Don't catch the top-level `Exception`.  What type of exception are you actually trying to map?

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/MarathonServiceScaler.java
> +        } catch (Exception e) {
Same comment

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/AppInstancePatcher.java
> +            URIBuilder uriBuilder = new URIBuilder(new URL(marathonUri.toURL(), "/v2/apps").toURI());
- `uriBuilder` should be `final`
- You jumped through hoops to pass `marathonUri` in as a `URI` only to have to get it back to a `URL`.

2018-05-31 14:51 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/AppInstancePatcher.java
> +        catch (Exception ex){
This will catch unchecked exceptions.

2018-05-31 14:52 UTC, dermot-hardy requested changes

2018-05-31 14:52 UTC, dermot-hardy commented on autoscale-scaler-marathon/src/main/java/com/hpe/caf/autoscale/scaler/marathon/AppInstancePatcher.java
> +public class AppInstancePatcher {
Class should probably be `final`.

2018-06-01 09:02 UTC, rado-straka commented
Updated

2018-06-01 12:00 UTC, dermot-hardy approved these changes

2018-06-01 12:01 UTC, merged