SCMOD-4709: Implemented RabbitMQ backoff and email alert.
Autoscaler/autoscaler pull request #28
Opened 2018-08-29 16:56 UTC by Anthony-McGreevy

2018-08-30 14:25 UTC, dermot-hardy requested changes
Comments so far, but I haven't looked at most of the files yet.

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-core/README.md
> +
- Shouldn't the prefix for all of these environment variables be `CAF_AUTOSCALER_` rather than just `CAF_`?
- It is not clear that this is only configuration relating to the new functionality
  - It is not clear how the new functionality is used - there is no mention of what labels to set
  - There is already a configuration section in this file
- The table doesn't look fantastic in the GitHub UI - let's change this to a list with details under each point (a bit like [this](https://github.com/WorkerFramework/worker-framework/blob/v1.6.0/release-notes-1.6.0.md#new-features))

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-core/README.md
> +| CAF_DISABLE_EMAIL_DISPATCH | NONE | This switch can be used to disable email alerts. If it is not set then emails will be sent to the monitored email address. |
I don't understand this one.  How can the default be 'NONE'?  Shouldn't it be 'TRUE' or 'FALSE'?

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-workload-rabbit/pom.xml
> +        </dependency>
Why is this dependency required?  This seems like a departure from the original architecture (which was using dependency inversion).

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-api/src/main/java/com/hpe/caf/api/autoscale/InstanceInfo.java
> +    private final String servicePriority;
Should this be an enumeration, or an integer?  How can strings have priorities?

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-api/src/main/java/com/hpe/caf/api/autoscale/WorkloadAnalyser.java
> +     * @throws ScalerException if it fails to determine memory utilisation due to not being able to connect to messaging platform's api.
Really if that is the reason for failure then it should probably throw an `IOException`, but I'm OK with this if it is more consistent with current exception usage.

2018-08-30 14:25 UTC, dermot-hardy commented on autoscale-api/src/main/java/com/hpe/caf/api/autoscale/WorkloadAnalyser.java
> +    String retrieveEmailContent(final String percentageMem);
- Parameter not described in JavaDoc
- If it is a percentage then why would it be a string?
- If this is returning the content of an e-mail then why would it be implemented in the workload analyser?

2018-08-30 19:19 UTC, dermot-hardy requested changes

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/README.md
> + All required configuration for this functionality and their defaults are listed below.
Is this meant to still be here?

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/README.md
> +This functionality will only work on services that have the label `autoscale.shutdownPriority` set in their app definitions. These labels are then used to determine which application should be shutdo
What values should it be set to?

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/README.md
> +### Email Alert Configuration
Should all the SMTP settings not be in this block?

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-api/src/main/java/com/hpe/caf/api/autoscale/InstanceInfo.java
> +    public int getPriority()
`getServicePriority()`

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-api/src/main/java/com/hpe/caf/api/autoscale/WorkloadAnalyser.java
> +     * @param percentageMem The percentage of the messaging platforms memory allows that has been used. This is passed as a string so that it can be added to the email body.
Respect the 138-character limit.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/AutoscaleScheduler.java
> +    private final EmailDispatcher emailDispatcher;
Generalize this - `autoscale-core` should not care how the administrator is notified.  Perhaps a message is posted on Slack for example.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +public class EmailDispatcher
Make the class `final` unless you are intending to inherit from it.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +    private Date lastSent;
Don't use the old `Date` structures - you should be using the Java 8 Date Time API.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +        final String usernameEnv = System.getenv("CAF_AUTOSCALER_SMTP_USERNAME");
When you separate this out into it's own component don't forget to update the prefixes again - i.e. variables used only from this module might start `CAF_AUTOSCALER_EMAIL_`.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +    private static final Object LOCK = new Object();
- Why is this lock `static`?
- Rename it after the resources that it is protecting - i.e. `lastEmailInfoLock` I think

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +            || (lastSent == null || ((date.getTime() - lastSent.getTime() <= 20 * 60 * 1000) && priorityThreshold == lastPriorityThreshold))) {
It looks like the logic that decides whether the e-mail should be sent in the e-mail dispatcher component.  If so then it is in the wrong place.  The decision that an alert needs to be sent should be taken centrally so the `EmailDispatcher` component is only concerned with actually dispatching the e-mail.

(Also note that this line goes over the 138-character limit)

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/EmailDispatcher.java
> +                }
This function is called `dispatchEmail()`, not `tryToDispatchEmail()`.  If it fails it should throw an exception so that the caller can decide what to do (which may well be to log the failure and move on - but only at that level can the decision be made - this component should assume that there may be a backup alert system).

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +    private final String disableEmailAlerts = System.getenv("CAF_AUTOSCALER_DISABLE_EMAIL_DISPATCH");
Should this not be a boolean, and given that it is being read from the environment it should be static.

Something like [this](https://github.com/WorkerFramework/worker-framework/blob/5d2c3a8ac985a1a381d11ce2e800e439d53bc2d8/worker-core/src/main/java/com/hpe/caf/worker/core/WorkerTaskImpl.java#L50) perhaps.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +    {
Whitespace on line,

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +        this.dispatchEmailAtStage = dispatchEmailAtStageEnv != null ? Integer.parseInt(dispatchEmailAtStageEnv) : 0;
Too much repeated logic - introduce helper functions.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +    private boolean analyseMemoryUse(final InstanceInfo instances) throws ScalerException
Rename function - this does much more than just analysis - it is also sending out alerts and reporting on the results.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +            }
Are any of these changes necessary, given that you've already checked the memory in `handleAnalysis()` just before this function was called.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +        this.stage3PriorityThreashold = stage3PriorityThreasholdEnv != null ? Integer.parseInt(stage3PriorityThreasholdEnv) : -1;
Repeated misspelling of "threshold".

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-dockerswarm-shared/src/main/java/com/hpe/caf/autoscale/endpoint/docker/DockerSwarmService.java
> +        return new InstanceInfo(replicasList.get(0), 0, blankServiceHosts, -1);
You wouldn't need to make these changes (and a lot of the test changes) if you overloaded the `InstanceInfo` constructor.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitWorkloadAnalyser.java
> +            + "From: Autoscaler\n";
Is this "From: Autoscaler" line intentional?  I found it a bit weird at the bottom of the e-mail content.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitWorkloadAnalyser.java
> +        return emailContenet;
There's no need to read this into an variable - you can just use `return` directly.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitSystemResourceMonitor.java
> +public class RabbitSystemResourceMonitor
Should be `final` unless there is a reason for it not to be.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitSystemResourceMonitor.java
> +            rabbitHost = rabbitHost.substring(0, rabbitHost.indexOf(":"));
Construct a `java.net.URI` and then use `getHost()`.

2018-08-30 19:19 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitSystemResourceMonitor.java
> +            throw new ScalerException("Unable to map response to status request.", ex);
What a pity to have lost the genuine nature of the exception.  Also, what does that message mean?

2018-09-03 19:20 UTC, Anthony-McGreevy commented
@dermot-hardy can you take another look at this.

2018-09-17 23:33 UTC, Anthony-McGreevy commented
@dermot-hardy I have updated the configuration to make the email dispatch stage a percentage of resource threshold instead. This has also been moved to the resource monitoring configs instead of the alert dispatch configs. The relevant documentation has been updated for this. Can you continue to review?

2018-09-25 18:11 UTC, dermot-hardy requested changes

2018-09-25 18:11 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/Alerter.java
> +        return (lastTime - System.currentTimeMillis()) >= (dispatchFrequency * 60 * 1000);
Logic doesn't seem right.  (Reads like it would always be `false`).

2018-09-26 08:33 UTC, Anthony-McGreevy commented
@dermot-hardy Timing logic has now been fixed.

2018-09-26 13:29 UTC, dermot-hardy approved these changes

2018-09-26 14:10 UTC, merged