Update readme with Docker Swarm Variant information
Autoscaler/autoscaler pull request #37
Opened 2018-12-07 15:58 UTC by trevorgetty

Updating the readme documentation with the docker swarm orchestrator variants.

2018-12-07 23:50 UTC, andyreidz commented on README.md
> +* autoscale-marathan-container
```suggestion
* autoscale-marathon-container
```

2018-12-11 09:13 UTC, andyreidz commented
@trevorgetty Thanks for the PR, can you complete a [CLA](https://github.com/CAFapi/CAFapi.github.io/blob/master/EntIT_CCLA%202018.docx) and email it to me?

2018-12-11 11:45 UTC, dermot-hardy requested changes

2018-12-11 11:45 UTC, dermot-hardy commented on README.md
> +### Marthan Variants
Marthan --> Mar**a**th**o**n

2018-12-12 13:25 UTC, trevorgetty commented on README.md
> +### Marthan Variants
I will go through all those spelling mistakes, that's what I get for copy/paste!

2018-12-12 13:28 UTC, trevorgetty commented
Hi guys, the CLA linked, has a section in it: 
_If you have not already done so, please complete and sign, then scan and email a pdf file of this Agreement to **[insert e-mail address here]**._

You may wish to insert your email address I think, I will update my local one with Andy's email?  
And I am getting our legal to agree to this, thanks. trev.

2019-10-17 11:43 UTC, thilagasanthosh commented
@dermot-hardy ,

This PR is with you . Do we need to include this change to release?
Please confirm.

2019-10-17 12:07 UTC, dermot-hardy commented
Check with @andyreidz what the situation with this is but if there is still a legal issue then no it shouldn't  hold up the release.

2019-10-17 12:10 UTC, andyreidz commented
Pleas go ahead with the release without this PR.

2021-05-17 14:14 UTC, xbreizh commented
Closing it as inactive and no information about a DCO signature

2021-05-17 14:14 UTC, closed without merging