Added scaling functions and rabbit query config
Autoscaler/autoscaler pull request #49
Opened 2019-12-17 11:14 UTC by Anthony-McGreevy

2019-12-17 12:05 UTC, Anthony-McGreevy commented
@dermot-hardy Just in case we decide it is worth doing a quick fix and patch release for.

2019-12-18 14:56 UTC, dermot-hardy requested changes

2019-12-18 14:56 UTC, dermot-hardy commented on autoscale-workload-rabbit/README.md
> + - memoryQueryRequestFrequency: The number of whole minutes that the service should wait between issuing requests to check rabbitmq's
Change to seconds.

2019-12-18 14:56 UTC, dermot-hardy commented on autoscale-marathon-container/src/main/config/cfg~caf~autoscaler~RabbitWorkloadAnalyserConfiguration.js
> +    memoryQueryRequestFrequency: getenv("CAF_AUTOSCALER_RABBITMQ_MEMORY_QUERY_FREQ") || 1,
Change default to 10 seconds.

2019-12-18 14:56 UTC, dermot-hardy commented on autoscale-workload-rabbit/src/main/java/com/hpe/caf/autoscale/workload/rabbit/RabbitSystemResourceMonitor.java
> +import org.slf4j.LoggerFactory;
Unused

2019-12-18 14:56 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +            if(shutdownPriority == -1 || shouldNotGoven(currentMemoryLoad, shutdownPriority)){
Should this be `shouldGovern`?

2019-12-18 14:56 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +            return 1;
Function faulty

2019-12-19 17:26 UTC, Anthony-McGreevy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +            return 1;
Fixed logic

2019-12-19 23:19 UTC, dermot-hardy requested changes

2019-12-19 23:19 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/GovernorImpl.java
> +                    } else if (!shouldGovern(currentMemoryLimitStage, shutdownPriority)) {
- Terminology is confusing (you're in a method called `govern` introducing a function called `shouldGovern`)
- Branch is duplicated (reorder to eliminate)
- I don't see why how this decision can be taken without reference to why are other service's minimum instances aren't met.

2019-12-20 16:08 UTC, dermot-hardy approved these changes
Ensure you definitely fix that return value one.

2019-12-20 16:08 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +    private int establishMemLimitReached(final double currentMemoryLoad)
3, 2, 1, 0

2019-12-20 16:08 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/GovernorImpl.java
> +    private boolean isScaledDownForMemoryManagement(final int currentMemoryLoadLimit, final int shutdownPriority)
- `static`
- Consider renaming to `shouldBeScaledDown`.

2019-12-20 16:08 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/GovernorImpl.java
> +                return true;
Should be `return false;`.

2019-12-20 16:08 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/GovernorImpl.java
> -
Add line back in

2019-12-23 10:23 UTC, merged