SCMOD-8597: Updated log messages
Autoscaler/autoscaler pull request #52
Opened 2020-02-10 18:20 UTC by Anthony-McGreevy

2020-02-11 09:49 UTC, michael-bryson approved these changes
This looks ok to me but lets have Rob take a look too, I can't add him to this PR though as he must not access to this repo.

2020-02-11 16:10 UTC, rob-duewer requested changes
I apparently don't have write access to this public repo, but yes, I can see the content.

It generally looks OK to me.  But I am concerned that you're eliminating the log entries at the info level; particularly on the scale down event.  We need those to be recorded at the standard prod level so we know not only when AS is scaling up, but also when it's actively scaling down.  (This allows us to determine when an instance fell off because it crashed or was otherwise terminated, and one stopped by AS normally.)  Scaling down events that would have been triggered when the total is already at the minimum do not need to be recorded.

I'm also concerned that at prod log level, this is not actually recording the case described in the ticket. What we need to know in the short log entry, that the scaling up event would have added X instances, but because of the configured maximum(Y); that was not possible; only Z instances were added to the count.  And Z can be zero, if the app is at its configured maximum.

The reason we need this (and at the info level) is so that we can parse the log if desired and look for these entries.  From an ops perspective, what this tells us is whether or not we have allocated sufficient resources to the cluster and set the maximum values for the app properly.  If we see a log line like this, we care very much about its frequency and the relative values of X, Y, and Z.  As an operator, this tells us how much pressure we have, allowing us to consider resource addition or other reconfiguration.

2020-02-11 16:10 UTC, rob-duewer commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +        LOG.debug("Service {} scaled down by {} instances.", serviceRef, amount);
Why is this at debug level?

2020-02-17 12:43 UTC, Anthony-McGreevy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/GovernorImpl.java
> +                        LOG.info("Service {} requested {} more instances but will only be scaled by {} as the service has a max instance "
@rob-duewer I have added the message you have requested at info level.

2020-02-17 15:24 UTC, merged