SCMOD-8752: Split autoscale back off
Autoscaler/autoscaler pull request #56
Opened 2020-04-24 13:31 UTC by Anthony-McGreevy

**Jira**: https://portal.digitalsafe.net/browse/SCMOD-8752
**Build**: http://sou-jenkins2.swinfra.net/job/Autoscaler/view/Developer/job/Autoscaler~autoscaler~SCMOD-8752~CI/

2020-04-24 15:04 UTC, dermot-hardy requested changes

2020-04-24 15:04 UTC, dermot-hardy commented on docs/pages/en-us/Getting-Started.md
> +`autoscale.scaleupbackoff`: Optional. Manages the number of intervals to skip after a scale up command is issued while monitoring. This prevents unusual values being considered when the system is in
You haven't put the `<br>`s like the other ones.

2020-04-24 15:04 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +            return false;
The logic doesn't seem right to me.  Why does these variable resets need to be done in the default case but not in the new cases you've added?

2020-04-28 01:01 UTC, dermot-hardy requested changes

2020-04-28 01:01 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +        backoffCount = 0;
Indenting screwed up here.

2020-04-28 01:01 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +                    backoff = false;
I don't get it.  Why would you be setting `backoff` to `false` when `shouldBackoff` is `true`?  Won't this stop the backing off?

2020-04-30 20:34 UTC, dermot-hardy requested changes
I'm sorry but the logic still doesn't look right to me.

2020-05-04 13:29 UTC, Anthony-McGreevy commented
Tested changes on larry and seen the modified scale up and scale down backoffs being set on the scaler threads for different apps, test carried out with 21,000 docs.

2020-05-04 13:59 UTC, dermot-hardy approved these changes

2020-05-04 13:59 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +                      action.getOperation(), serviceRef, action.getAmount());
Pointless whitespace change

2020-05-04 13:59 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +                      action.getOperation(), serviceRef, action.getAmount());
Pointless whitespace change

2020-05-04 13:59 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +
Pointless whitespace change

2020-05-04 13:59 UTC, dermot-hardy commented on autoscale-core/src/main/java/com/hpe/caf/autoscale/core/ScalerThread.java
> +    private boolean backoffComplete()
The function naming is a little confusing here.  It seems strange to have an `isBackoffComplete()` a) without the `is` and b) even though there may never have been any backoff.

2020-05-05 10:15 UTC, merged