SCMOD-14517: Update master/slave to active/standby
Autoscaler/autoscaler pull request #77
Opened 2021-08-24 13:51 UTC by kleyton-ohare

https://portal.digitalsafe.net/browse/SCMOD-14517

2021-08-24 13:52 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=Autoscaler&REPO_NAME=autoscaler&BRANCH_NAME=SCMOD-14517) to go ahead and create the build...

2021-08-24 13:56 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/Autoscaler/job/Autoscaler~autoscaler~SCMOD-14517~CI

2021-08-24 14:17 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/Autoscaler_CI_autoscaler_SCMOD-14517

2021-08-24 20:39 UTC, dermot-hardy requested changes
There must be more required.  I can see this in the Overview page of the documentation:

![image](https://user-images.githubusercontent.com/20627297/130686743-ce6e9000-be5d-4098-b8dd-0ac104e52a0c.png)

2021-08-25 10:45 UTC, kleyton-ohare commented
I have already done these changes in [SCMOD-14251](https://portal.digitalsafe.net/browse/SCMOD-14251) but I think they will be reflected in the online documentation once this repo is released because this [page](http://sou-jenkins2.swinfra.net:8080/job/Autoscaler/job/Autoscaler~autoscaler~SCMOD-14517~CI/) from this branch already shows the updates.
However, I did forget to update the API (Javadocs). I will work on it now.

2021-08-25 11:58 UTC, kleyton-ohare commented
The [API](https://autoscaler.github.io/autoscaler/pages/en-us/autoscaleApiDoc/index.html) page does not need to be updated because the changes were made in autoscale-core module and this API is only for autoscale-api.

2021-08-25 13:30 UTC, dermot-hardy approved these changes

2021-08-25 14:43 UTC, merged