CAF-2941: Remove closed-source dependencies from Autoscaler
Autoscaler/autoscaler pull request #9
Opened 2017-06-15 16:44 UTC by arogan92

* Container updated to use java8-with-tini image.
* exec arguments updated to work with tini
* Unnecessary dependencySets removed
* doc-site-compiler updated to use newly open-sourced version
* Updated the <image> tags to push to caf-internal instead of rh7-artifactory

2017-06-15 16:45 UTC, arogan92 commented
Developer builds are successful
http://sou-jenkins2.hpeswlab.net:8080/job/Autoscaler/view/Developer/job/Autoscaler~autoscaler~CAF-2941~CI/1/console

2017-06-15 16:45 UTC, arogan92 commented
Jira:  https://jira.autonomy.com/browse/CAF-2941

2017-06-16 04:26 UTC, dermot-hardy requested changes
The `tini` dependency is still present --> https://github.com/Autoscaler/autoscaler/blob/e1b2898ea904c5eba26a8c3a2c5bd68780c8c361/autoscale-container/pom.xml#L86

2017-06-16 04:26 UTC, dermot-hardy commented on autoscale-container/pom.xml
> -                                            <dependencySet>
Why is this first dependency set removed?

2017-06-16 14:29 UTC, arogan92 commented
Changes made after feedback

2017-06-16 16:01 UTC, mulhollandc approved these changes

2017-06-16 18:48 UTC, dermot-hardy requested changes

2017-06-16 18:48 UTC, dermot-hardy commented on autoscale-container/pom.xml
> +                                            <dependencySet>
Erroneous whitespace added

2017-06-16 18:51 UTC, merged